language: node_js
node_js:
- node
env:
  global:
    secure: pttRGxkSqRXfR9sNYbdY+IMlgiPh2MdF1Dq42eYczDfzAxzBVWWnvMrYq6lCXLu0rBODDu506rrOCGvdOknUjZTqV7ngv7Ryx1hSqVv2eljI9TrLLxgOHOSWNz+ZyzFcjtA3BDY/kUo4W+a5MVJS7BEcDCqXSIooB4yelwgoEaS8ujbv1lS78AZX9ABsh8gEVYpVvaK7O4AT8wbsU61qRXBSLhoESxft1dz0SnaIFj3sHz4sy3BoYXYMYInvWPc55/Tg6FvYfuBqAnEPXDWUtncC2UTr6jNNv+LCq+wZbsbalw5gK0gFftvCAK838kZz3KN67cZXmAphFvalw4xr3J57fH9M1z0FaeNGB/SNzdtno+c6v2rxDGyr+vDZS8qVPGgn8GrhhTWxmvo9vPxj/BxiMbubvfFROseYh1IULH2QGgy++PirtoF3C9fq2EPp8W1e1AfkWqwPczS1nMCbEzshh+Pvpfp0JkFgpHCcmlAiZeYTWWQkMrwix85OYByRJBUImbrdajztlXet86vvix6frWtE6WdFzqkDNSM2nBhqP/E/PiTjN3PDlgwy8H+OXFtlvcuMtd0lRcDEPbig41uE8x2IE4g0iH24J+ONR72rQK2kB0E8vn9YTyqCFvGmo8ijdTNF/5KILvvm+GBaSooXTkwkfq6udZV+86zcyYY=
